### ISSUE TITLE
Combine with beatdruid info ? 

### ISSUE THREAD

**Issue by ajboni** [ajboni/airwindows-cheatsheet#11]
http://beatdruid.com/index.php?title=Airwindows:_Plugin_Catalog

License is compatible, it makes sense .

**Comment by iguatemigarin** [comment]
Seems a nice idea, but beatdruid is offline at the moment 🤷

**Comment by ajboni** [comment]
> Seems a nice idea, but beatdruid is offline at the moment shrug
what about this? 
https://web.archive.org/web/20200218040135/http://beatdruid.com/index.php?title=Airwindows:_Plugin_Catalog

Unfortunately each dedicated section is not available in the archive :(

**Comment by iguatemigarin** [comment]
Sorry that it took me so long to come back.

Well, Chris is releasing new plugins every damn week (the man is restless!). Which brings the point of automating the cheatsheet.

What do you think, shall we give a try? I'll open another issue to talk about it.

**Comment by ajboni** [comment]
Closing in favor of #29
