### ISSUE TITLE
Some links point to old versions of plugins

### ISSUE THREAD

**Issue by tikihorea** [ajboni/airwindows-cheatsheet#12]
Some links point to old versions of plugins.
An example is PurestDrive. Click on the plugin name leads to _http://www.airwindows.com/purestdrive/_ instead of _http://www.airwindows.com/purestdrive-vst/_

Maybe have the website first look for links that have VST in them?
Then only choose links without VST if it can't find any with VST in the link?

**Comment by ajboni** [comment]
> Some links point to old versions of plugins.
> An example is PurestDrive. Click on the plugin name leads to _http://www.airwindows.com/purestdrive/_ instead of _http://www.airwindows.com/purestdrive-vst/_
> 
> Maybe have the website first look for links that have VST in them?
> Then only choose links without VST if it can't find any with VST in the link?

Good find, I guess leaving that job to the client is a little harsh and could make it slower.
I've made a prop to 'override' the default url: 

```json
  {
    Name: "BussColors4",
    Type: "Saturation",
    Use: "Mixing",
    Description: "The Airwindows console emulations",
    Comments: "etc...",
    Url: "http://www.airwindows.com/busscolors-4/",
  },
```

Check: 
https://github.com/ajboni/airwindows-cheatsheet/commit/3b8c91b86ba32f76cf8b8818b7c5fb002b55ed09
https://github.com/ajboni/airwindows-cheatsheet/commit/96c2cb20c4b45973fd9e65a3e4835652f2b54d93

**Comment by tikihorea** [comment]
Also, there's a need to choose the link with Redux in the link rather than a simple one. :D

**Comment by ajboni** [comment]
> Also, there's a need to choose the link with Redux in the link rather than a simple one. :D

Indeed, yes, let's use the `Url` property to redirect to specific urls and use the auto generated as a fallback mechanism
