### ISSUE TITLE
Cheatsheet update automation

### ISSUE THREAD

**Issue by iguatemigarin** [ajboni/airwindows-cheatsheet#15]
Well, it doesn't look like Chris will stop releasing new plugins any time soon - which is amazing!

I think would be great if the cheatsheet was always updated with the latest releases.

This is relatively easy using any scrap mechanism to update the `database.js`. The only missing information is the `Type` and `Use` properties, which would need a manual input still.

My first thought is using the WP built in REST endpoints (e.g. `https://www.airwindows.com/wp-json/wp/v2/posts`) to collect the data.

Any thoughts?

**Comment by ajboni** [comment]
Hi! I really like the idea!!. 
\We just only need to be  a little careful about copyright (we should check the licensing of the site) and we need some sort of summary for each plugin. 
Also  we could add a "colaborate" or "recommendations pending" on empty properties so we can maybe encourage collaboration .  I might help with the CI part. Just need to research if github offers some sort of schedule action.

**Comment by ajboni** [comment]
Closing in favor of #29
